### ISSUE TITLE
Understanding the convention

### ISSUE THREAD

**Issue by karneaud** [BoilWP/WooCommerce-Extension-Boilerplate-Light#9]
Hello @seb86 ,

I managed to install the plugin and so far works. I'm hoping I can have some dialog with you in an attempt understand some of the files as it relates to organising my code. I'm trying to build a shipping method for woo commerce

**Comment by seb86** [comment]
@karneaud I have not worked on this boilerplate in sometime. The code is outdated so I'm actually surprised to hear you say it still works. If you would still like to consult with me then you can [hire me via Codeable](https://codeable.io/developers/sebastien-dumont/).
